### ISSUE TITLE
Drivetrain

### ISSUE THREAD

**Issue by CheezBallzPi** [RoboEagles4828/2018Robot#2]
When you get the time, @RoboEagles4828/new-programmers should study up on how to make a drivetrain. This should be good to help you guys get used to everything and whatever. Make a new branch called `feature/drivetrain`, probably... maybe put your name if you want to work separately: `feature/drivetrain-jackie`. Or you could work together. Feel free to look through all the other repositories for tips.

**Comment by alebcay** [comment]
Bonus points/assignment: If you figure it all out, try to make the drivetrain into a library (i.e. like a module of code that can be used elsewhere) and compile a JAR that can be imported into the robot code from year to year so that the same code doesn't have to be re-written over and over again.

Obviously, just a hobby project to try in spare time. Anyone that decides to take it on will probably get to know the code really well in the process.

**Comment by CheezBallzPi** [comment]
May or may not have forgotten to tell them about Github Issues. We'll see.

**Comment by tamablevirus** [comment]
I got an email notification, I'll work on this when I have time.

**Comment by CheezBallzPi** [comment]
Made a branch and class for drivetrain.

**Comment by CheezBallzPi** [comment]
@tamablevirus: I'm taking over this project since you aren't at the shop today.

**Comment by CheezBallzPi** [comment]
@jacksondm33 Is this finished?

**Comment by CheezBallzPi** [comment]
Ah, if you merge, don't forget to say "Closes #(this number)"

**Comment by jacksondm33** [comment]
Haven't tested the DriveTrain completely, but so far it works. I also need to test other code in the branch but I should be able to do that today.

**Comment by jacksondm33** [comment]
I did forget to say "Closes #(this number)"
